### ISSUE TITLE
Support MySQL 8.0.18

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/moco#121]
## What

MOCO is tested for MySQL 8.0.20 because that version will be used in our first productive use case.
MySQL 8.0.18 is going to be used for development and test, so support MySQL 8.0.18.

## How

Describe how to address the issue.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by masa213f** [comment]
The IntermediatePrimary feature does not work in MySQL 8.0.21 or later.
The tablespace is corrupted after Clone.
https://bugs.mysql.com/bug.php?id=102137

So, for now, we will limit the supported MySQL versions to 8.0.18 and 8.0.20 only.
