### ISSUE TITLE
Support one and five replica numbers

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/moco#175]
## What

Currently, MOCO support only MySQLCluster that has 3 replicas.
We should support working with 1 and 5 replicas.

## How

- Support 1 and 5 replicas.
  - Maybe, a cluster having 5 replicas works fine with the current MOCO.  But, we need to add test to confirm it.
  - A cluster with only one instance doesn't work until fixing the reconciliation procedure.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
Will be done in #220
