### ISSUE TITLE
Implement graceful restart

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/moco#187]
## What

Implement graceful restart started by `kubectl moco graceful-restart` and reconciler.

https://github.com/cybozu-go/moco/blob/v0.5.1/docs/design.md#how-to-implement-the-initialization-of-mysql-pods-with-avoiding-unnecessary-restart-at-the-operator-update

> If users want to change their MySQL cluster configuration, users basically should execute mysql commands like SET GLOBAL .... In case that we cannot avoid restarting MySQL cluster to apply changes in the user-defined ConfigMap, we should execute a command like kubectl moco graceful-restart CLUSTER.

Though this design has been changed, we still need graceful restart.

## How

Add `preStop` hook in order to change the role to a replica before stopping mysqld.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
will be done in #220
