### ISSUE TITLE
Support increasing replica numbers

### ISSUE THREAD

**Issue by kfyharukz** [cybozu-go/moco#209]
## What

Support increasing replica numbers.  The supported cases are:
- 1 to 3
- 3 to 5

## How

Fix the reconciliation procedure to increase replicas using clone operation.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
will be done in #220
