### ISSUE TITLE
Ensure the reconciliation compatibility with versioning

### ISSUE THREAD

**Issue by kfyharukz** [cybozu-go/moco#212]
## What

Ensure the reconciliation compatibility with versioning.

## How

- Add reconciler ver. to status of `MySQLCluster` resource
- Add reconciler ver. to reconciler func name
- Add the above design to `design.md`

Note that:
- Must not to update `StatefulSet` spec automatically
- Retain the old version of reconciler func to ensure the compatibility
- Notify users that `StatefulSet` should be updated via such as `MySQLCluster` status

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
Will be done in #220
