### ISSUE TITLE
Provide upgrade path of moco-agent

### ISSUE THREAD

**Issue by kfyharukz** [cybozu-go/moco#213]
## What

When upgrading `moco-agent`, the StatefulSet must be modified. It leads to restart Pod.
Avoid any downtime, we should provide upgrade path of moco-agent.

## How

Note that:
- Must not to update `StatefulSet` spec automatically
- Notify users that `StatefulSet` should be updated via such as `MySQLCluster` status

Maybe, this issue is related to #212 

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
We determined to restart mysqld Pods when moco-agent is updated.
We'd try our best to avoid updating moco-agent too frequently.
