### ISSUE TITLE
Guaranteed QoS

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/moco#235]
## What

Currently, MOCO users cannot make MySQL pods to have [Guaranteed QoS](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed) because MOCO does not limit resources to some containers.

Improve MOCO to allow users to make Guaranteed MySQL Pods.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by arosh** [comment]
According to our experience of running MOCO for the past half year in our development environment, the max memory usages by containers except for mysqld are as follows. The memory usages are observed by `container_memory_working_set_bytes` from cAdvisor.

| container | max memory usage |
| ---------- | ---------------------- |
| agent (moco-agent) | 60 MiB |
| slow-log (fluent-bit) | 9 MiB |
| mysqld_exporter | 38 MiB |
