### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by inductor** [cybozu-go/moco#248]
**Describe the bug**

After following setup instruction, I tried to install the guaranteed example and I got the following error at the init container.

```
$ kubectl logs moco-test-0 moco-init
mysqld: Can't create directory '/var/lib/mysql/data/' (OS errno 13 - Permission denied)
2021-05-24T19:44:33.022939Z 0 [System] [MY-013169] [Server] /usr/local/mysql/bin/mysqld (mysqld 8.0.24) initializing of server in progress as process 12
2021-05-24T19:44:33.024090Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/data/ is unusable. You can remove all files that the server added to it.
2021-05-24T19:44:33.024138Z 0 [ERROR] [MY-010119] [Server] Aborting
2021-05-24T19:44:33.024316Z 0 [System] [MY-010910] [Server] /usr/local/mysql/bin/mysqld: Shutdown complete (mysqld 8.0.24)  Source distribution.
Error: exit status 1
exit status 1
```

It's on Digital Ocean managed Kubernetes service.

**Environments**
- Version: do-kube-1.20.2-do.0 / latest moco
- OS: Debian

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by ymmt2005** [comment]
@inductor 
It seems that your storage provisioner sets the filesystem permission bits to something that allows writes only to `root`.
Could you give it another try with `spec.securityContext.fsGroup: 10000` in the Pod template?

**Comment by inductor** [comment]
@ymmt2005 Thanks it worked like a charm!

**Comment by ymmt2005** [comment]
I'd add a tip to the user manual.  Thank you for reporting.

**Comment by northboys** [comment]
Still get error

root@mitclusternode01:/home/mit/Kubernetes/Moco# kubectl logs -n moco moco-test-1  moco-init
mysqld: Can't create directory '/var/lib/mysql/data/' (OS errno 13 - Permission denied)
2021-09-15T07:30:43.635259Z 0 [System] [MY-013169] [Server] /usr/local/mysql/bin/mysqld (mysqld 8.0.26) initializing of server in progress as process 13
2021-09-15T07:30:43.636343Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/data/ is unusable. You can remove all files that the server added to it.
2021-09-15T07:30:43.636374Z 0 [ERROR] [MY-010119] [Server] Aborting
2021-09-15T07:30:43.636471Z 0 [System] [MY-010910] [Server] /usr/local/mysql/bin/mysqld: Shutdown complete (mysqld 8.0.26)  Source distribution.
Error: exit status 1
exit status 1

**Comment by ymmt2005** [comment]
@northboys Could you show your YAML?

**Comment by northboys** [comment]
apiVersion: moco.cybozu.com/v1beta1
kind: MySQLCluster
metadata:
  namespace: moco
  name: test
spec:
  # replicas is the number of mysqld Pods.  The default is 1.
  replicas: 3
  podTemplate:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - mysql
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - test
            topologyKey: "kubernetes.io/hostname"
      containers:
      # At least a container named "mysqld" must be defined.
      - name: mysqld
        image: quay.io/cybozu/mysql:8.0.26
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
      securityContext:
        fsGroup: 10000
  volumeClaimTemplates:
  # At least a PVC named "mysql-data" must be defined.
  - metadata:
      name: mysql-data
    spec:
      storageClassName: longhorn
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

**Comment by northboys** [comment]
apiVersion: moco.cybozu.com/v1beta1
kind: MySQLCluster
metadata:
  namespace: moco
  name: test
spec:
  replicas: 3
  podTemplate:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - mysql
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - test
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: mysqld
        image: quay.io/cybozu/mysql:8.0.26
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
      securityContext:
        fsGroup: 10000
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      storageClassName: longhorn
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

**Comment by northboys** [comment]
`apiVersion: moco.cybozu.com/v1beta1
kind: MySQLCluster
metadata:
  namespace: moco
  name: test
spec:
  # replicas is the number of mysqld Pods.  The default is 1.
  replicas: 3
  podTemplate:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - mysql
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - test
            topologyKey: "kubernetes.io/hostname"
      containers:
      # At least a container named "mysqld" must be defined.
      - name: mysqld
        image: quay.io/cybozu/mysql:8.0.26
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
      securityContext:
        fsGroup: 10000
  volumeClaimTemplates:
  # At least a PVC named "mysql-data" must be defined.
  - metadata:
      name: mysql-data
    spec:
      storageClassName: longhorn
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
`

**Comment by ymmt2005** [comment]
@northboys Thanks.  I edited your text for readability.

**Comment by northboys** [comment]
<img width="530" alt="Screen Shot 2021-09-15 at 15 54 25" src="https://user-images.githubusercontent.com/38155944/133403236-e17aeb64-4a96-4542-b4af-2652ab27a350.png">

**Comment by ymmt2005** [comment]
Thanks.  I cannot find anything wrong with your YAML.  Sorry.

**Comment by northboys** [comment]
Is there a solution?

**Comment by ymmt2005** [comment]
Unfortunately, I haven't used longhorn.  So I have no idea.

**Comment by northboys** [comment]
okay then, i use default storage and successful install

**Comment by northboys** [comment]
how to make this writable, I got an error like this

root@mitclusternode01:/home/mit/Kubernetes/Moco# kubectl moco -n enggano-system mysql -it -u moco-admin ha-mysql-moco
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 24
Server version: 8.0.26 Source distribution

Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> create database engganoplatform;
ERROR 1290 (HY000): The MySQL server is running with the --super-read-only option so it cannot execute this statement
mysql>

**Comment by ymmt2005** [comment]
What does `kubectl get -n enggano-system mysqlcluster ha-mysql-moco` output?

**Comment by ymmt2005** [comment]
This is a closed issue.
If you want to continue the discussion, please use Discussions.
