### ISSUE TITLE
Support Switchover

### ISSUE THREAD

**Issue by dulltz** [cybozu-go/moco#26]
## What

Enable to switchover through SwitchoverJob CR and kubectl-moco.

## How

- Add SwitchoverJob CRD.
- Implement the new controller for SwitchoverJob
  - Note that while any SwitchoverJob is running, another SwitchoverJob can be created but the operator waits for the completion of running jobs.
  - Terminate and switch over MySQL servers gracefully.
- Extend kubectl-moco plugin to start switchover.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by masa213f** [comment]
note: https://bozuman.cybozu.com/k/#/space/3801/thread/38189/2726285/4402107

**Comment by ymmt2005** [comment]
will be done in #220
