### ISSUE TITLE
Document the procedure to increase volume size

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/moco#265]
## What

Kubernetes currently does not allow users to increase the storage sizes in `spec.volumeClaimTemplates`
of an already created StatefulSet.  There is an ongoing [KEP](https://github.com/kubernetes/enhancements/pull/1848), though.

Since MOCO creates a StatefulSet for each MySQL cluster, users cannot increase the storage size declared in
`spec.volumeClaimTemplates[].spec.resources.requests["storage"]` of MySQLCluster.

To increase the size, users need to follow the instructions shown below:

1. Resize all PVCs manually
2. Edit MySQLCluster and change the requested volume size
3. Delete StatefulSet w/o deleting Pods
    - `kubectl delete sts moco-xxx --cascade=orphan`

Afterward, `moco-controller` will successfully recreate StatefulSet with the new size.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ClaudiuLSH** [comment]
Can't this be automated? Running manual operations on a production deployment should be limited as much as possible maybe?

[Here is how another project handled this](https://github.com/zalando/postgres-operator/blob/a6d4f23f90fe12822a19e758ff400233c9212e00/pkg/cluster/volumes.go#L46).

**Comment by ymmt2005** [comment]
@ClaudiuLSH Yes, this can be automated.

Such a feature enhancement is preferable to documentation like this.

**Comment by ymmt2005** [comment]
@d-kuro can we close this now?

**Comment by d-kuro** [comment]
@ymmt2005 thanks!, I have completed the task and will close
