### ISSUE TITLE
Update operator to be able to upgrade MySQL version

### ISSUE THREAD

**Issue by tapih** [cybozu-go/moco#27]
## What

Automate MySQL version upgrade when the image version in `MySQLCluster.spec.podTemplate` is upgraded

## How

MySQL software upgrade is triggered by changing container image specified in `MySQLCluster.spec.podTemplate`.
In this section, the name of `StatefulSet` is assumed to be `mysql`.

1. Switch primary to the pod `mysql-0` if the current primary is not `mysql-0`.
2. Update and apply the `StatefulSet` manifest for `mysql`, to trigger upgrading the replicas as follows:
  - Set `.spec.updateStrategy.rollingUpdate.partition` as `1`.
  - Set new image version in `.spec.template.spec.containers`.
3. Wait for all the replicas to be upgraded.
4. Switch primary to `mysql-1`.
5. Update and apply the `StatefulSet` manifest to trigger upgrading `mysql-0` as follows:
  - Remove `.spec.updateStrategy.rollingUpdate.partition`.
6. Wait for `mysql-0` to be upgraded.

This logic is considered only for upgrading. Supporting downgrade is TBD.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
will be implemented with the standard `RollingUpdate` strategy.
