### ISSUE TITLE
Add MySQL 8.0.26 Support

### ISSUE THREAD

**Issue by ysksuzuki** [cybozu-go/moco#285]
## What

MySQL 8.0.26 has been released, so we're going to add its support.
https://dev.mysql.com/downloads/mysql/

## How

Modify documents and add 8.0.26 to the test matrix.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
I have prepared quay.io/cybozu/mysql:8.0.26 .
https://quay.io/repository/cybozu/mysql?tab=tags
