### ISSUE TITLE
Why only 5 MySQL instances are supported？

### ISSUE THREAD

**Issue by Asteven-zn** [cybozu-go/moco#286]
Moco MySQL is a really great project, hope the number of slave MySQL instances can be increased

**Comment by ymmt2005** [comment]
There are no reasons to limit the support up to 5.
The codebase is generic enough to add support for 7, 9, or even more.

The only problem? might be e2e tests on GitHub Actions where the virtual machine has a limited amount of resources.

What do you think if we add support for 7 and 9 instances w/o e2e tests?

**Comment by Asteven-zn** [comment]
Thank you for your reply！

The problem now is that the value of "spec: replicas:" in the cluster yaml file is limited to 1, 3 and 5.Value can be set to a custom quantity

During GitHub actions E2E testing, can set a small number of values. Do you think so？

In this way,can start the cluster through the yaml file and add the number of slaves！

**Comment by ymmt2005** [comment]
> During GitHub actions E2E testing, can set a small number of values. Do you think so？

Yes, we'd like to stay using 5 instances in E2E because of the limited resources.

So, we may loosen the limitation of `spec.replicas` to any positive odd number.
Does it sound good?

**Comment by Asteven-zn** [comment]
I think so. It's a good way

**Comment by Asteven-zn** [comment]
When will this function be updated?

**Comment by ymmt2005** [comment]
No due is set yet.
Would you like to create a pull request for this?

**Comment by Asteven-zn** [comment]
Yes, the cluster needs to add more MySQL slave instances

**Comment by ymmt2005** [comment]
Cool.  So please send your PR.  We will review it quickly.

**Comment by Asteven-zn** [comment]
I'm not fully familiar with code yet. It may be later

**Comment by d-kuro** [comment]
Hi @Asteven-zn.
I'm ready to make a Pull Request.
Is it okay to take over this issue?

**Comment by Asteven-zn** [comment]
hello @d-kuro.
Sorry, I'm busy recently. I can't take over other projects for the time being
