### ISSUE TITLE
Write User manual and other necessary documents

### ISSUE THREAD

**Issue by tapih** [cybozu-go/moco#32]
## What

Write user manual and other documents if needed.

## How

Write user manual and other documents if needed.
Update Feature in README.md.

In user-manual.md, please include the following:
- The operator has a reserved name for the mysqld container in `StatefulSet.spec.podTemplate.spec.containers`.
  Please ensure users to give a container with the container name. 
- The operator has a reserved names for the entrypoint container in `StatefulSet.spec.podTemplate.spec.initContainers`.
  Please ensure users NOT to give a container with the container name. 

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
will be done in #228
