### ISSUE TITLE
Manual installation procedure of kubectl-moco does not work.

### ISSUE THREAD

**Issue by pddg** [cybozu-go/moco#340]
Parentheses is used. However, curly brackets seems to be expected.
https://github.com/cybozu-go/moco/blob/c9013554e92fbc97f4d29b0beb67413b16484ab9/docs/install-plugin.md?plain=1#L53

**Expected behavior**

The values will be filled with pre-defined variables and kubectl-moco will be downloaded.

**Actual behavior**

Zsh (and also Bash) try to exec commands named VERSION, OS and ARCH.

```
❯ curl -L -sS https://github.com/cybozu-go/moco/releases/download/$(VERSION)/kubectl-moco_$(VERSION)_$(OS)_$(ARCH).tar.gz \
  | tar xz -C /usr/local/bin kubectl-moco
zsh: command not found: VERSION
zsh: command not found: VERSION
zsh: command not found: OS
ARCH: Can't find any plists for ARCH
tar: Error opening archive: Unrecognized archive format
```

**Comment by ymmt2005** [comment]
Thank you.  will be addressed by #341
