### ISSUE TITLE
QoS Class should be Guaranteed

### ISSUE THREAD

**Issue by arosh** [cybozu-go/moco#368]
**Describe the bug**
The QoS class of MySQL pods is Burstable whereas it is preferred to be Guaranteed.

```text
$ kubectl -n dev-dbre describe pod moco-stage0-fujita-1-0 | grep -i qos
QoS Class:                   Burstable
$
```

**Environments**
- Version: v0.10.9
- OS: Flatcar Container Linux (Stable)

**To Reproduce**
1. Deploy MySQLCluster
2. kubectl describe pod PODNAME | grep QoS

**Expected behavior**
QoS Class is Guaranteed.

**Additional context**
According to our experience of running MOCO for the past half year in our development environment, the max memory usages by containers except for mysqld are as follows. The memory usages are observed by `container_memory_working_set_bytes` from cAdvisor.

| container | max memory usage |
| ---------- | ---------------------- |
| agent (moco-agent) | 60 MiB |
| slow-log (fluent-bit) | 9 MiB |
| mysqld_exporter | 38 MiB |

**Comment by ymmt2005** [comment]
@arosh Could you move this to #235 ?

**Comment by arosh** [comment]
@ymmt2005 
I transcribed the max memory usages to #235. Thanks.
