### ISSUE TITLE
Better instructions for custom docker builds

### ISSUE THREAD

**Issue by vanpelt** [cybozu-go/moco#382]
## What

The current instructions for custom docker builds could be improved.  It should be rare that users need to build custom containers, but adding an example dockerfile / build logic would be helpful.  To be clear if I had to choose between better custom build instructions or just making the existing builds support arm64 and amd64 I would choose the latter.

## How

I recently needed to build an arm64 mysql image for my M1 Mac dev environment, here's the Dockerfile I ended up with:

> Note: I first needed to copy the [moco-init](https://github.com/cybozu/neco-containers/tree/main/mysql/moco-init) directory into my docker build workspace.  One could either add something like `Dockerfile.custom` in the mysql directory of neco-containers, or provide an easier way to get the source code for moco-init into a build env.  Maybe with a tarball in a github release or something?

```dockerfile
ARG BASE_UBUNTU=focal-20220113
FROM k8s.gcr.io/pause:3.2 AS pause
FROM ubuntu:${BASE_UBUNTU} AS base

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  locales \
  tzdata \
  openssl \
  netbase \
  apt-utils \
  apt-transport-https \
  libreadline8 \
  ca-certificates \
  curl \
  && apt-get -y upgrade \
  && rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8 \
  && update-locale LANG=en_US.UTF-8 \
  && echo "Etc/UTC" > /etc/timezone \
  && dpkg-reconfigure -f noninteractive tzdata

FROM base AS mysql
# Inspiration: https://cybozu-go.github.io/moco/custom-mysqld.html#how-to-build-mysqld
# https://dev.mysql.com/downloads/mysql/
ARG MYSQL_VERSION=8.0.28
RUN apt-get update \
  && apt-get -y --no-install-recommends install build-essential libssl-dev cmake libncurses5-dev libjemalloc-dev libnuma-dev libaio-dev pkg-config \
  && curl -fsSL -O https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-boost-${MYSQL_VERSION}.tar.gz \
  && tar -x -z -f mysql-boost-${MYSQL_VERSION}.tar.gz \
  && cd mysql-${MYSQL_VERSION} \
  && mkdir bld \
  && cd bld \
  && cmake .. -DBUILD_CONFIG=mysql_release -DCMAKE_BUILD_TYPE=Release -DWITH_BOOST=$(ls -d ../boost/boost_*) -DWITH_NUMA=1 -DWITH_JEMALLOC=1 \
  && make -j $(nproc) \
  && make install

FROM golang:1.17-focal AS golang
COPY ./moco-init /tmp/moco-init
RUN cd /tmp/moco-init && mkdir -p /tmp/bin && GOBIN=/tmp/bin go install -ldflags="-w -s" .

FROM base
COPY --from=pause /pause /usr/local/bin/pause
COPY --from=mysql /usr/local/mysql /usr/local/mysql
COPY --from=golang /tmp/bin/moco-init /usr/local/mysql/bin/moco-init

RUN apt-get update \
  && apt-get install -y --no-install-recommends libjemalloc2 libnuma1 libaio1 \
  && rm -rf /var/lib/apt/lists/* \
  && mkdir -p /var/lib/mysql \
  && chown -R 10000:10000 /var/lib/mysql

ENV PATH=/usr/local/mysql/bin:"$PATH"
VOLUME /var/lib/mysql
ENTRYPOINT ["mysqld"]
EXPOSE 3306 33060 33062 8080
USER 10000:10000

CMD ["/bin/bash"]
```

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by zoetrope** [comment]
Thanks. I agree with your suggestion.
But we maintainers don't have M1 Mac.
Please wait a bit until we get a M1 Mac.
