### ISSUE TITLE
The words "master" and "slave" in MySQL will be replaced by "source" and "replica" in the future.

### ISSUE THREAD

**Issue by shunki-fujita** [cybozu-go/moco#385]
## What
The words "master" and "slave" in MySQL will be replaced by "source" and "replica" in the future.

The old wording has been deprecated since 8.0.23 and will be removed in the future.
(It has not yet been announced when they will be removed.)
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-23.html#mysqld-8-0-23-deprecation-removal

Therefore, moco should fix them in the future.

**Comment by ymmt2005** [comment]
@shunki-fujita 
We have been aware of that and deliberately chosen "primary" and "replica".
For use of "master/slave" in SQL, they are required for supporting old MySQL versions (8.0.18 or so).
