### ISSUE TITLE
Can Moco support replication between multiple Kubernetes Clusters to support Geographical redundancy?

### ISSUE THREAD

**Issue by brainwang** [cybozu-go/moco#422]
MySQL has a similar ClusterSet feature.

**Comment by ymmt2005** [comment]
There is a basic support for this in moco. We use this setup to replicate two moco clusters running in two k8s clusters.
https://cybozu-go.github.io/moco/usage.html#creating-a-cluster-that-replicates-data-from-an-external-mysqld

I don't have any plan for a more advanced feature.
