### ISSUE TITLE
Support configuring nodeSelector of moco-controller

### ISSUE THREAD

**Issue by uqix** [cybozu-go/moco#441]

**Comment by masa213f** [comment]
@uqix 
Hi, thank you for the request.
Just to confirm, you want to configure the nodeSelector of moco-controller when installing by Helm, don't you?

**Comment by uqix** [comment]
Yes, thanks

**Comment by masa213f** [comment]
Released.

https://github.com/cybozu-go/moco/releases/tag/chart-v0.3.0
https://github.com/cybozu-go/moco/blob/chart-v0.3.0/charts/moco/CHANGELOG.md#030---2022-09-12
