### ISSUE TITLE
Rapid reconciliation loop for kind Service

### ISSUE THREAD

**Issue by paveq** [cybozu-go/moco#449]
**Describe the bug**
Moco operator enters into constant and infinite reconciliation loop for kind Service, flooding Kubernetes API server with requests, can causing lot of load in Calico nodes as well and various issues in cluster.

Reconciliation itself seems to succeed, and I see no other changes on the Service objects except quickly increasing resourceVersion. It is unclear what triggers operator to enter reconciliation rapidly.

**Environments**
-  kubernetes v1.23.6+k3s1
- Moco v0.12.1 installed via helm chart

**To Reproduce**
Bit unclear what are exact conditions this occurs, but potentually to reproduce the behavior, run MySQLCluster with 1 replica (single node setup).

**Expected behavior**
Reconciliation of Services happen only occasionally and when needed.

**Log output**
```
{"level":"info","ts":1661932491.8314571,"logger":"controller.mysqlcluster","msg":"reconciled Service","reconciler group":"moco.cybozu.com","reconciler kind":"MySQLCluster","name":"x-m2-prod-magento","namespace":"x-m2-prod","serviceName":"moco-x-prod-magento-replica"}
{"level":"info","ts":1661932491.8870642,"logger":"controller.mysqlcluster","msg":"reconciled Service","reconciler group":"moco.cybozu.com","reconciler kind":"MySQLCluster","name":"y-prod-magento","namespace":"y-prod","serviceName":"moco-y-prod-magento-primary"}
{"level":"info","ts":1661932491.9274118,"logger":"controller.mysqlcluster","msg":"reconciled Service","reconciler group":"moco.cybozu.com","reconciler kind":"MySQLCluster","name":"z-prod-magento","namespace":"z-prod","serviceName":"moco-z-prod-magento-primary"}
```

**Comment by masa213f** [comment]
Thank you. Let me check.
