### ISSUE TITLE
change registry for pull image from local registry

### ISSUE THREAD

**Issue by DFazeli** [cybozu-go/moco#462]
## What

How can I change `ghcr.io/cybozu-go/moco-agent:0.7.1` and `quay.io/cybozu/fluent-bit:1.9.7.2` to local registry.
e.g:
`local/moco-agent:0.7.1`
`local/fluent-bit:1.9.7.2`

**Comment by ymmt2005** [comment]
You can change them by adding command-line flags to `moco-controller`.
https://github.com/cybozu-go/moco/blob/main/docs/moco-controller.md

Specifically,
> --agent-image string               The image of moco-agent sidecar container
> --backup-image string              The image of moco-backup container
> --fluent-bit-image string          The image of fluent-bit sidecar container
> --mysqld-exporter-image string     The image of mysqld_exporter sidecar container

It seems we don't have a Helm variable to give these flags.
Am I correct? @d-kuro @masa213f

**Comment by ymmt2005** [comment]
@DFazeli 
This is an example procedure to make moco use custom images.

1. Download raw manifests from https://github.com/cybozu-go/moco/releases/latest/download/moco.yaml
2. Search `kind: Deployment` in the downloaded manifest.
3. Add `args` to `moco-controller` container as follows:

```yaml
      containers:
(snip)
        name: moco-controller
        args:
        - --agent-image=local/moco-agent:0.7.1
```

Then, apply the manifest with `kubectl apply -f moco.yaml`.
ref. https://cybozu-go.github.io/moco/setup.html#install-using-raw-manifests

Helm installation does not allow you to add these arguments.

**Comment by masa213f** [comment]
Yes. Currently, we cannot set the custom images for sidecars as Helm variables.
I want to update the Chart in the next release :)

**Comment by ymmt2005** [comment]
In #466, you can change the container image to be used with Helm.

@masa213f can we close this now?
