### ISSUE TITLE
Log the reason why "cluster state is Lost"

### ISSUE THREAD

**Issue by arosh** [cybozu-go/moco#494]
**Describe the bug**

I sent SIGABRT to mysqld on the primary instance to observe behavior of failover by MOCO. However, an unintentional "cluster state is Lost" was logged and the cluster was delayed in becoming available until the original primary instance was restarted without failover being performed.

**Environments**
- Version: MOCO chart-v0.4.1
- OS: Flatcar Container Linux (stable)

**To Reproduce**
1. Deploy MySQLCluster
2. Exec `kubectl exec -it $primary -c mysqld -- /bin/sh -c "kill -ABRT 1"`

**Expected behavior**

Log the reason why "cluster state is Lost".

https://github.com/cybozu-go/moco/blob/e19e4d323ee3bff6b9cbf7fe883732a857d810fc/clustering/status.go#L472-L499

**Comment by masa213f** [comment]
@arosh 
Are you trying to failover of an empty cluster?
If so, it's a limitation. MOCO cannot failover empty clusters.

When the primary is inaccessible and replicas have no data,
MOCO cannot determine whether replicas lost data by any accident or the cluster is empty.

**Comment by arosh** [comment]
@masa213f 
> MOCO cannot failover empty clusters.

Our cluster was empty... Thank you.
