### ISSUE TITLE
Why `MySQLClusterSpec.backupPolicyName` is required ?

### ISSUE THREAD

**Issue by pddg** [cybozu-go/moco#524]
`backupPolicyName` is marked as `Required: true` in the document.
https://cybozu-go.github.io/moco/crd_mysqlcluster_v1beta1.html#mysqlclusterspec
https://cybozu-go.github.io/moco/crd_mysqlcluster_v1beta2.html#mysqlclusterspec

It seems to be optional since the type of `backupPolicyName` is `*string`.
There were no problems when I actually used the `MySQLCluster` without `backupPolicyName`.

**Comment by umezawatakeshi** [comment]
As you pointed out, it is a bug of documentation. We will fix it.
