### ISSUE TITLE
Support MySQL 8.0.33 and 8.0.34

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/moco#549]
## What

Support MySQL 8.0.33 and 8.0.34
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-33.html
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-34.html

## How

Describe how to address the issue.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
@masa213f Cc: @arosh @shunki-fujita 
Now that MySQL 8.0 has become a long-term support release, can we only
support the latest version of 8.0? What do you think?

**Comment by shunki-fujita** [comment]
@ymmt2005 
According to the documentation, two versions are supported from the latest version. (and the version used internally).
https://github.com/cybozu-go/moco/blob/main/DEVELOP.md#running-tests

If the version used internally is included in the support, there is no problem with supporting only the latest version.

@masa213f 
I would like to hear from the maintainers who decided on this policy.

**Comment by masa213f** [comment]
@ymmt2005 @shunki-fujita 
Sorry for the late reply.
As you commented, it might be enough to test only the latest version of v8.0.
I will do the CI update in another task.
