### ISSUE TITLE
Question - Is there a way to pause reconciliation after a moco upgrade ? 

### ISSUE THREAD

**Issue by donch** [cybozu-go/moco#572]
Hi, 

We use Moco with dozens of MySQL clusters on the same Kubernetes cluster. When updating Moco, all the mysqlclusters are restarted (probably to upgrade the moco agent?).
Is there a way to disable these reconciliations and perform them one by one? 

Thanks

**Comment by ymmt2005** [comment]
I think @d-kuro is working on it.
https://github.com/cybozu-go/moco/blob/main/docs/designdoc/clustering_stop.md

**Comment by masa213f** [comment]
@ymmt2005 
The current design will stop the reconciliation and the cluster manager for a MySQLCluster when using this feature.
As far as this question is concerned, it seems sufficient to stop only reconciliation.

@d-kuro 
Can I request a design change?
It is better to enable stopping the reconciliation and the cluster manager individually.

**Comment by d-kuro** [comment]
@donch 

I have added a feature in the following pull request to suppress the reconciliation and clustering of the MySQLCluster.
While this feature requires manual operation, it allows updating each MySQLCluster one by one during the moco upgrade.

* https://github.com/cybozu-go/moco/pull/578

This change is included in v0.20.0 of moco.

https://github.com/cybozu-go/moco/releases/tag/v0.20.0
