### ISSUE TITLE
Support Kubernetes 1.28

### ISSUE THREAD

**Issue by rdegez** [cybozu-go/moco#588]
Hi,

Kubernetes 1.28.0 was released on Aug 15th 2023
Could the next Moco release include support for this version ?

Regards,

**Comment by rdegez** [comment]
Replying to myself:
I didn't face any issue deploying moco on a 1.28.2 cluster from the helm-chart so... I guess it's supported already! 
Missed that, sorry for the noise.

**Comment by ymmt2005** [comment]
By "support", we mean we've tested it on our CI.
1.28 has not been tested in that sense, but I guess it should work with any recent Kubernetes releases.
