### ISSUE TITLE
How do I customize all images address not just mysqld?

### ISSUE THREAD

**Issue by comeonyang43** [cybozu-go/moco#646]
k8s clusters in intranet

**Comment by d-kuro** [comment]
@comeonyang43 
The controller provides a option to replace images. This allows you to customize images, not just mysqld, by utilizing this option.

> ```
> Flags:
> ...
>       --agent-image string                The image of moco-agent sidecar container
>       --backup-image string               The image of moco-backup container
>       --fluent-bit-image string           The image of fluent-bit sidecar container
>       --mysqld-exporter-image string      The image of mysqld_exporter sidecar container
> ```

https://cybozu-go.github.io/moco/moco-controller.html

**Comment by masa213f** [comment]
Questions answered.
