### ISSUE TITLE
A backup of another sourcename with the same prefix is restored.

### ISSUE THREAD

**Issue by yoheinbb** [cybozu-go/moco#647]
**Describe the bug**
If there are backups with sourcename xx-1 and xx-11, restoring by specifying xx-1 and after the **last date and time** of the xx-1 backup will restore xx-11.

**Expected behavior**
If sourcename is xx-1, only the backup of xx-1 is restored.

**Additional context**
Backup paths xx-1 and xx-11 are both listed because the object is retrieved by prefix.
https://github.com/cybozu-go/moco/blob/1e5089dea41fa1127210ed7cba70f6f6070a1d60/pkg/bucket/s3.go#L112-L120

**Comment by morimoto-cybozu** [comment]
Resolved by https://github.com/cybozu-go/moco/pull/648.
