### ISSUE TITLE
Istio sidecar injection causes readiness probe to fail

### ISSUE THREAD

**Issue by vsliouniaev** [cybozu-go/moco#657]
**Describe the bug**
I'm trying to set up the simplest cluster with just a single pod in a cluster.
When I have sidecar injection disabled the cluster comes up ok.
When I turn on sidecar injection and recreate the pod I seeing the readiness probes start failing.
I can remote into the container and I see the readiness endpoint is returning an error message about replication:
```
$ curl localhost:9081/readyz
failed to get replica status: failed to show slave status: sql: no rows in result set
```

I'm not sure what happens with this readiness check or where configuration for it could be altered. I'm a bit hesitant to straight-up disable it entirely.

(There are other issues with the operator using the pod IP address to do its own health checking, but I feel like that's a separate problem since it's external)

**Environments**
- Version: v0.20.2
- OS: istio 1.18

**To Reproduce**
Try create a simple cluster in an istio mesh

**Expected behavior**
Container should not fail readiness probes with a single pod when istio sidecar is injected.

**Additional context**

**Comment by zoetrope** [comment]
@vsliouniaev 
I was able to reproduce the same issue.

Istio prohibits direct communication between Pods that bypasses the Service.
Therefore, it seems that the communication between the Moco Controller and the MySQL Pod is failing.
To resolve this issue, port 33062 must be defined as a headless service, and the MOCO Controller must operate MySQL through it.

If you need a workaround, please add an annotation to `podTemplate` of your MySQLCluster as follows:

```yaml
apiVersion: moco.cybozu.com/v1beta2
kind: MySQLCluster
spec:
  podTemplate:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: "33062"
```

**Comment by vsliouniaev** [comment]
I have added this annotation to the pod.
I have also checked that the headless service used by the statefulset has port `33062` on it.
I don't think this issue is resolved, the pods are still not coming up with 3/4 containers ready.

The changes that I see committed for this pull request and the comments are talking about communication between the moco controller and the pod. However the pod itself is failing to come up because of a failed readiness check.
Does this readiness check somehow depend on communication between the pod and the controller?

**Comment by ymmt2005** [comment]
> Does this readiness check somehow depend on communication between the pod and the controller?

Yes. The readiness check failed because the mysqld instance is in read-only mode.
The readiness probe logic considers a read-only mysqld instance a replica, so it
checked the replica status.

However, since this is the only instance in the cluster, the mysqld pod should be
set to read-write mode, which the moco-controller is responsible for. We identified
the problem was coming from the moco-controller being not able to connect to the
admin port of mysqld (because of Istio), so it failed to set the mysqld instance
read-write.

**Comment by ymmt2005** [comment]
BTW,
> I have also checked that the headless service used by the statefulset has port 33062 on it.

The headless service did not have port 33062 before PR #658.

**Comment by vsliouniaev** [comment]
> BTW,
> 
> > I have also checked that the headless service used by the statefulset has port 33062 on it.
> 
> The headless service did not have port 33062 before PR #658.

I had added that port by hand once I saw some error logs in the controller.

> @vsliouniaev I was able to reproduce the same issue.
> 
> Istio prohibits direct communication between Pods that bypasses a Service. Therefore, it seems that the communication between the Moco Controller and the MySQL Pod is failing. To resolve this issue, port 33062 must be defined as a headless service, and the MOCO Controller must operate MySQL through it.
> 
> If you need a workaround, please add an annotation to `podTemplate` of your MySQLCluster as follows:
> 
> ```yaml
> apiVersion: moco.cybozu.com/v1beta2
> kind: MySQLCluster
> spec:
>   podTemplate:
>     metadata:
>       annotations:
>         traffic.sidecar.istio.io/excludeInboundPorts: "33062"
> ```

I'm not a fan of dropping istio here and in any case this doesn't work by itself when the controller also has an istio sidecar. The istio-sidecar logs from the controller side suggest I need to set up some extra configuration here:
```
{
  "upstream_transport_failure_reason": "TLS_error:_268435703:SSL_routines:OPENSSL_internal:WRONG_VERSION_NUMBER"
}
```

If I leave istio to handle the port this works fine, but I do have an issue with the sidecar reaching sqld. I think this is because setting `admin_address` to the pod's name makes requests unroutable. When I tested this with a custom image that uses `localhost` instead I didn't have to drop TLS anywhere.

**Comment by ymmt2005** [comment]
OK. So, we've resolved one problem, but there is still one more problem, right?

**Comment by vsliouniaev** [comment]
I think it may work in certain cases where there is no enforced mTLS in the mesh with the extra port from https://github.com/cybozu-go/moco/pull/658
Though it does not work in my case and I cannot turn off mTLS for the entire mesh.

There is a way to get this working end-to-end, which I describe at the bottom

### Tests
#### Original Issue

```
mysql-admin port exists on service : FALSE
excludeInboundPorts                : FALSE
```
This is the original issue described.
Fails - since there is no route to the endpoint through istio on the inbound side the request times out.
mysql proxy error: `"response_code_details":"filter_chain_not_found"`

#### Treat mysql as external service
```
mysql-admin port exists on service : FALSE
excludeInboundPorts                : TRUE
```
This works in my setup but may not work in all setups. I think the route is handled as being outside the mesh.


#### Add admin port
This is with https://github.com/cybozu-go/moco/pull/658
```
mysql-admin port exists on service : TRUE
excludeInboundPorts                : FASE
```
Fails - the istio proxy being unable to reach mysqld on the pod's external IP address.
mysql proxy error: `"upstream_transport_failure_reason": "delayed_connect_error:_111"`

#### Bypass istio on mysql side
```
mysql-admin port exists on service : TRUE
excludeInboundPorts                : TRUE
```
This fais with a TLS error on the operator side: `"upstream_transport_failure_reason": "TLS_error:_268435703:SSL_routines:OPENSSL_internal:WRONG_VERSION_NUMBER"`
I can fix this by creating a destinationrule
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-mysql-admin
  namespace: test-namespace
spec:
  host: *.test-namespace.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 33061
      tls:
        mode: DISABLE
```

### End-to-end working mTLS
```
mysql-admin port exists on service : TRUE
excludeInboundPorts                : FALSE
```
Normally this would result in `delayed_connect_error`. But I tested that this can be fixed by getting the agent to use `localhost` instead of the pod's IP addres when communicating with the mysql admin port.
