### ISSUE TITLE
rpl_semi_sync_master_timeout Can it be changed to configurable

### ISSUE THREAD

**Issue by sona-yuan** [cybozu-go/moco#716]
## What

Describe what this issue should address.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
No.

It's deliberately designed not to be configurable.
See docs/clustering.md for details.

**Comment by sona-yuan** [comment]
However, if we consider RTO, some services that want higher continuity can accept sacrificing some data consistency. May I ask if we consider changing it to a configurable item in the future
