### ISSUE TITLE
When initializing the MySQL cluster, the cluster status is at 2/3, and the replication establishment fails with an error message source server_id is 0

### ISSUE THREAD

**Issue by sona-yuan** [cybozu-go/moco#739]
**Describe the bug**

**Environments**
- Version:0.23.1
- OS:linux

**To Reproduce**
1. apply mycluster.yaml
2. 2024-09-10T10:05:35.980547Z 714 [ERROR] [MY-010557] [Repl] Error reading packet from server for channel '': Misconfigured source - source server_id is 0 (server_errno=1236)
2024-09-10T10:05:35.980564Z 714 [ERROR] [MY-013114] [Repl] Replica I/O for channel '': Got fatal error 1236 from source when reading data from binary log: 'Misconfigured source - source server_id is 0', Error_code: MY-013114
![image](https://github.com/user-attachments/assets/4c7fc6b6-224c-4c68-b6d0-9e6ad011e928)

**Expected behavior**

**Additional context**

**Comment by takara9** [comment]
@sona-yuan 

> When initializing the MySQL cluster, the cluster status is at 2/3, 
> and the replication establishment fails with an error message 
> source server_id is 0 20 hours ago

We want to more information to understand you facing issue. Clould you provide us mycluster.yaml and your cluster environment ?

**Comment by takara9** [comment]
@sona-yuan 
I'm closing this because I haven't received a reply. Please reopen it if necessary.
