### ISSUE TITLE
After the master-slave switch, the change master information of the new master is not cleared

### ISSUE THREAD

**Issue by sona-yuan** [cybozu-go/moco#740]
**Describe the bug**

**Environments**
- Version:0.23.1
- OS:linux

**To Reproduce**
![image](https://github.com/user-attachments/assets/66791ce9-8abc-4c80-b0a4-4e2ff8152b28)
![image](https://github.com/user-attachments/assets/87b29a2c-1a2f-4e55-8dbd-b009a2b28ee2)

**Expected behavior**
After the master-slave switch, there should be no data showing the slave status on the new master

**Additional context**

**Comment by YZ775** [comment]
@sona-yuan 
MOCO does not perform `RESET SLAVE ALL` after promoting to master on switchover, so it is an implementation specification that the SLAVE information remains.

If you would like MOCO to perform RESET SLAVE ALL after switchover and you are willing to create PR, we're welcome.

**Comment by YZ775** [comment]
This issue has been inactive for a while, so we are closing it. If you have any updates or further information, please feel free to reopen it.
