### ISSUE TITLE
Supporting MySQL 9.0 and 9.1

### ISSUE THREAD

**Issue by mhkarimi1383** [cybozu-go/moco#761]
## What

These versions are marked as stable so we can support them I think

**Comment by zeroalphat** [comment]
Thank you for the report. 
As per our policy, we support only LTS versions of MySQL. 
While MySQL 9.0 and 9.1 are GA, they are Innovation Releases and are not supported.

https://github.com/cybozu-go/moco?tab=readme-ov-file#supported-software
